-- CreateTable
CREATE TABLE "EventForm" (
    "id" TEXT NOT NULL,
    "status" "TravelRequestStatus" NOT NULL DEFAULT 'PENDING',
    "company" TEXT,
    "firstName" TEXT NOT NULL,
    "lastName" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "phone" TEXT NOT NULL,
    "eventType" TEXT NOT NULL,
    "participants" TEXT,
    "projectDescription" TEXT,
    "departureDate" TIMESTAMP(3),
    "returnDate" TIMESTAMP(3),
    "dateFlexibility" BOOLEAN NOT NULL DEFAULT false,
    "dateComments" TEXT,
    "accommodationLevel" TEXT NOT NULL DEFAULT 'Milieu de gamme',
    "hasAccommodation" BOOLEAN NOT NULL DEFAULT true,
    "roomType" TEXT NOT NULL DEFAULT 'Double',
    "hasMeetingRoom" BOOLEAN NOT NULL DEFAULT true,
    "accommodationComments" TEXT,
    "destination" TEXT NOT NULL,
    "hasTransport" BOOLEAN NOT NULL DEFAULT true,
    "departureCity" TEXT,
    "activities" TEXT[],
    "activitiesComments" TEXT,
    "objectives" TEXT[],
    "objectivesComments" TEXT,
    "halfDays" INTEGER NOT NULL DEFAULT 0,
    "budgetPerPerson" TEXT,
    "budgetComments" TEXT,
    "contactPreference" TEXT NOT NULL DEFAULT 'Email',
    "message" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "EventForm_pkey" PRIMARY KEY ("id")
);
