-- AlterTable
ALTER TABLE "Tour" ADD COLUMN     "pricePerPerson" DOUBLE PRECISION,
ALTER COLUMN "priceOriginal" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "priceDiscounted" SET DATA TYPE DOUBLE PRECISION;
